...
  viewCount: Number(r.view_count),
  durationSeconds: r.duration_seconds != null ? Number(r.duration_seconds) : null,
  publishedAt: r.published_at?.toISOString ? r.published_at.toISOString() : String(r.published_at),
...
